### ISSUE TITLE
Synchronizace mapy po změně projektu

### ISSUE THREAD

**Issue by fzadrazil** [LESPROJEKT/qgis-layman-plugin#26]
Pokud už mám mapový projekt synchronizovaný v QFieldCloud a provedu nějakou změnu, např. přidám atribut do mapované vrstvy, musím mít možnost změny promítnout do QField.

**Comment by honza2** [comment]
V Layman pluginu jsou nyní 2 možnosti jak načíst projekt - z Laymana a Z QFieldu. Layman na rozdíl od Qfield využívá primárně služby wms, wfs, kdežto qfield má nativní formát geopackage, pro práci offline. Z tohoto důvodu nastává rozpor. Vyřešeno způsobem, že dochází ke kontrole providera vrstvy a pokud se snažíme přepsat původní geopackage pomocí WMS, tak je to ošetřeno hláškou. Z toho vypadávají 2 vstupy pro patch projektu. První je načtení přes tlačítko synchronizace, nebo načíst původní projekt z lokálního disku. U druhé možnosti je zároveň ošetřena chyba k možnosti znovupřihlášení k serveru.

**Comment by fzadrazil** [comment]
Pomohla by podpora geopackage ze strany Laymana? Tedy i když by se tím nevyřešil rozpor, že mapová kompozice Laymana obsahuje primárně reference na WMS/WFS, alespoň podkladová data by byla jednotná. Můžeme probrat při hovoru.
